version: '2'
services:
  
  
  webapp:
    build: .
    command: "npm start"
    ports:
     - "8080:8080"

    links:
     - memcached

  memcached:
    image:
      memcached
    ports:
     - "11211:11211"

